name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: compile and run all tests
      run: ./.github/scripts/testall.sh
      shell: bash
    - name: cleanup everything
      run: ./.github/scripts/cleanall.sh
      shell: bash
